'use strict';

export const GET_COUNTERS_REQUEST = 'GET_COUNTERS_REQUEST';
export const GET_COUNTERS_SUCCESS = 'GET_COUNTERS_SUCCESS';
export const GET_COUNTERS_FAIL = 'GET_COUNTERS_FAIL';

export const USE_COUNTER = 'USE_COUNTER';
export const UNUSE_COUNTER = 'UNUSE_COUNTER';

export const GET_CARDS_REQUEST = 'GET_CARDS_REQUEST';
export const GET_CARDS_SUCCESS = 'GET_CARDS_SUCCESS';
export const GET_CARDS_FAIL = 'GET_CARDS_FAIL';

export const GET_SITES_REQUEST = 'GET_SITES_REQUEST';
export const GET_SITES_SUCCESS = 'GET_SITES_SUCCESS';
export const GET_SITES_FAIL = 'GET_SITES_FAIL';

export const GET_SITE_REQUEST = 'GET_SITE_REQUEST';
export const GET_SITE_SUCCESS = 'GET_SITE_SUCCESS';
export const GET_SITE_FAIL = 'GET_SITE_FAIL';

export const ADD_SITE_REQUEST = 'ADD_SITE_REQUEST';
export const ADD_SITE_SUCCESS = 'ADD_SITE_SUCCESS';
export const ADD_SITE_FAIL = 'ADD_SITE_FAIL';

export const EDIT_SITE_REQUEST = 'EDIT_SITE_REQUEST';
export const EDIT_SITE_SUCCESS = 'EDIT_SITE_SUCCESS';
export const EDIT_SITE_FAIL = 'EDIT_SITE_FAIL';

export const DELETE_SITE_REQUEST = 'DELETE_SITE_REQUEST';
export const DELETE_SITE_SUCCESS = 'DELETE_SITE_SUCCESS';
export const DELETE_SITE_FAIL = 'DELETE_SITE_FAIL';

export const SAVE_SETTINGS_REQUEST = 'SAVE_SETTINGS_REQUEST';
export const SAVE_SETTINGS_SUCCESS = 'SAVE_SETTINGS_SUCCESS';
export const SAVE_SETTINGS_FAIL = 'SAVE_SETTINGS_FAIL';

export const GET_SETTINGS_REQUEST = 'GET_SETTINGS_REQUEST';
export const GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS';
export const GET_SETTINGS_FAIL = 'GET_SETTINGS_FAIL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const CONNECT_GOOGLE_SUCCESS = 'CONNECT_GOOGLE_SUCCESS';
export const CONNECT_GOOGLE_FAIL = 'CONNECT_GOOGLE_FAIL';
export const CONNECT_YANDEX_SUCCESS = 'CONNECT_YANDEX_SUCCESS';
export const CONNECT_YANDEX_FAIL = 'CONNECT_YANDEX_FAIL';
